# Generated by Django 3.2.5 on 2021-11-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
