# Generated by Django 3.2.5 on 2021-11-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211129_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='maintenance_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='work_assigned',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
